model: simplediff
n_epochs: 200
# n_retrain: 100
n_retrain: 510
n_samples: 10000
prop_old: 0.
exp_name: collapse
checkpoint_freq: 10
n_gen_samples: 5000
cold_start: False
device: cpu
last_run: False
dataname: 8gaussians
nb_new: -1
save_gen_samples: True
