model: simplediff
n_epochs: 100
n_retrain: 25
n_samples: 5000
prop_old: 0.
exp_name: collapse
checkpoint_freq: 1
n_gen_samples: 1000
cold_start: False
device: cpu
last_run: False
dataname: 8gaussians
nb_new: -1
batch_size: 128
save_gen_samples: True
