model: ddpm
n_epochs: 40
n_retrain: 25
n_samples: 5000
prop_old: 0.
exp_name: collapse
checkpoint_freq: 1
checkpoint_nb_gen: 1000
cold_start: False
device: cpu
last_run: False
dataname: cifar
nb_new: -1
batchsize: 128
val_batchsize: 128
dataroot: "/network/datasets/cifar10.var/cifar10_torchvision/"
nworkers: 1
dim: 32
