model: ddpm
n_epochs: 2
n_finetune_epochs: 2
n_retrain: 25
n_samples: 5000
prop_old: 0.
exp_name: cifar
checkpoint_freq: 1
checkpoint_nb_gen: 1000
cold_start: False
device: cpu
last_run: False
dataname: cifar
nb_new: -1
batchsize: 768
val_batchsize: 768
nworkers: 1
dim: 32
save_gen_samples: False
