model: ddpm
n_epochs: 1
n_finetune_epochs: 1
n_retrain: 5
num_timesteps: 1000
sampling_timesteps: 50
n_samples: 5000
prop_old: 0.
exp_name: cifar_debug
checkpoint_freq: 1
n_gen_samples: 50000
cold_start: False
last_run: False
dataname: cifar
nb_new: -1
batchsize: 768
batchsize_sampling: 4096
val_batchsize: 768
nworkers: 1
dim: 32
save_gen_samples: False
prototype: False
use_ddim: True  # Idk if this is used
